@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Diogo Saran",
  "email": "DiogoSaran@didi.com.br",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "DiogoSaran@didi.com.br",
  "password": "123456"
}

###

# @name create_service
POST {{baseUrl}}/services
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Corte de cabelo",
    "description": "Corte de cabelo masculino",
    "price": 30,
    "duration": 30,
    "observations": "Não cortar o cabelo ruim"
}

###

# @name update_service
PATCH  {{baseUrl}}/services/14f5fa39-ffeb-4394-96ae-df1e58d040dd
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Corte de cabelo",
    "description": "Corte de cabelo masculino",
    "price": 30,
    "duration": 30,
    "observations": "Não cortar o cabelo ruim"
}
