@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

@organizationId = fd76a81d-38a6-4c58-8b51-c46488faa729

@serviceId = {{create_service.response.body.service._id.value}}

@spaceOfServiceId = {{create_space_of_service.response.body.spaceOfService._id.value}}

@customerId = 0750bbf7-e91d-4e3a-8fc9-57a8603c0cac

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Diogo Saran",
  "email": "DiogoSaran@didi.com.br",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "DiogoSaran@didi.com.br",
  "password": "123456"
}

###

# @name create_organization
POST {{baseUrl}}/organizations
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Barbearia do Zezé1"
}

###

# @name update_organization
PATCH {{baseUrl}}/organizations/{{organizationId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Barbearia do Ze"
}

###

# @name create_schedule
POST {{baseUrl}}/schedules
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "organizationId": "{{organizationId}}",
  "days": [
    {
      "weekDay": 0,
      "startHour": 480,
      "endHour": 1080
    },
    {
      "weekDay": 1,
      "startHour": 480,
      "endHour": 1080
    },
    {
      "weekDay": 2,
      "startHour": 480,
      "endHour": 1080
    },
    {
      "weekDay": 3,
      "startHour": 480,
      "endHour": 1080
    },
    {
      "weekDay": 4,
      "startHour": 480,
      "endHour": 1080
    },
    {
      "weekDay": 5,
      "startHour": 480,
      "endHour": 1080
    },
    {
      "weekDay": 6,
      "startHour": 0,
      "endHour": 0
    }
  ]
}

###

# @name create_service
POST {{baseUrl}}/services
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "organizationId": "{{organizationId}}",
  "name": "Corte de cabelo4",
  "description": "Corte de cabelo masculino",
  "price": 30,
  "duration": 30,
  "observations": "Não cortar o cabelo ruim"
}

###

# @name update_service
PATCH  {{baseUrl}}/services/id/{{serviceId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "organizationId": "{{organizationId}}",
  "name": "Corte de cabelo5",
  "description": "Corte de cabelo masculino",
  "price": 30,
  "duration": 30,
  "observations": "Não cortar o cabelo ruim"
}

###

# @name create_space_of_service
POST {{baseUrl}}/spaceofservices
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "organizationId": "{{organizationId}}",
  "name": "Espaço 1",
  "description": "Espaço para atendimento 1"  
}

###

# @name create_appointment
POST {{baseUrl}}/appointments
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "date": "2025-08-10T07:00:00Z",
  "description": "Agendamento de teste",
  "observations": "Observações do agendamento",
  "organizationId": "{{organizationId}}",
  "spaceOfServiceId": "{{spaceOfServiceId}}",
  "serviceId": "{{serviceId}}",
  "customerId": "{{customerId}}"
}

###

# @name list_appointments_by_month
GET {{baseUrl}}/appointments/list/{{organizationId}}/month?month=8&year=2025
Content-Type: application/json
Authorization: Bearer {{authToken}}